# -*- coding: utf-8 -*-
"""LR_1_task_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnXZ1C38PrwIqCNUfgZgYvz7w_41KCzj
"""

# Імпорт необхідних бібліотек
import numpy as np
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split, cross_val_score
from utilities import visualize_classifier

# Вхідний файл, який містить дані
input_file = 'data_multivar_nb.txt'

# Завантаження даних із вхідного файлу
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]

# Створення наївного байєсівського класифікатора
classifier = GaussianNB()

# Тренування класифікатора
classifier.fit(X, y)

# Прогнозування значень для тренувальних даних
y_pred = classifier.predict(X)

# Обчислення якості класифікатора
accuracy = 100.0 * (y == y_pred).sum() / X.shape[0]
print("Accuracy of Naive Bayes classifier =", round(accuracy, 2), "%")

# Візуалізація результатів роботи класифікатора
visualize_classifier(classifier, X, y)

# Розбивка даних на навчальний та тестовий набори
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

# Створення нового екземпляра класифікатора
classifier_new = GaussianNB()

# Тренування класифікатора на навчальному наборі
classifier_new.fit(X_train, y_train)

# Прогнозування результатів на тестовому наборі
y_test_pred = classifier_new.predict(X_test)

# Обчислення якості нового класифікатора
accuracy = 100.0 * (y_test == y_test_pred).sum() / X_test.shape[0]
print("Accuracy of the new classifier =", round(accuracy, 2), "%")

# Візуалізація роботи нового класифікатора
visualize_classifier(classifier_new, X_test, y_test)

# Використання крос-валідації для оцінювання класифікатора
num_folds = 3

# Оцінка точності (accuracy)
accuracy_values = cross_val_score(classifier, X, y, scoring='accuracy', cv=num_folds)
print("Cross-validated Accuracy:", round(100 * accuracy_values.mean(), 2), "%")

# Оцінка точності (precision)
precision_values = cross_val_score(classifier, X, y, scoring='precision_weighted', cv=num_folds)
print("Cross-validated Precision:", round(100 * precision_values.mean(), 2), "%")

# Оцінка повноти (recall)
recall_values = cross_val_score(classifier, X, y, scoring='recall_weighted', cv=num_folds)
print("Cross-validated Recall:", round(100 * recall_values.mean(), 2), "%")

# Оцінка F1-міри (F1 score)
f1_values = cross_val_score(classifier, X, y, scoring='f1_weighted', cv=num_folds)
print("Cross-validated F1 Score:", round(100 * f1_values.mean(), 2), "%")