# -*- coding: utf-8 -*-
"""LR_1_task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ddAVuRmmTMm1ZAxTn5_AyJ-tGWTtabeR
"""

# Імпортуємо необхідні бібліотеки
import numpy as np
from sklearn import preprocessing

# Визначаємо вхідні дані
input_data = np.array([
    [5.1, -2.9, 3.3],
    [-1.2, 7.8, -6.1],
    [3.9, 0.4, 2.1],
    [7.3, -9.9, -4.5]
])

# 2.1.1 Бінаризація даних
# Виконуємо бінаризацію з порогом 2.1
data_binarized = preprocessing.Binarizer(threshold=2.1).transform(input_data)
print("\nBinarized data:\n", data_binarized)

# 2.1.2 Виключення середнього
# Виведення середнього значення та стандартного відхилення перед обробкою
print("\nBEFORE:")
print("Mean =", input_data.mean(axis=0))
print("Std deviation =", input_data.std(axis=0))

# Масштабування даних (виключення середнього значення та нормалізація дисперсії)
data_scaled = preprocessing.scale(input_data)

# Виведення середнього значення та стандартного відхилення після обробки
print("\nAFTER:")
print("Mean =", data_scaled.mean(axis=0))
print("Std deviation =", data_scaled.std(axis=0))

# 2.1.3 Масштабування Min-Max
# Масштабуємо дані до діапазону [0, 1]
scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0, 1))
data_scaled_minmax = scaler_minmax.fit_transform(input_data)
print("\nMin-Max scaled data:\n", data_scaled_minmax)

# 2.1.4 Нормалізація даних
# Нормалізація за L1 нормою
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
print("\nL1 normalized data:\n", data_normalized_l1)

# Нормалізація за L2 нормою
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nL2 normalized data:\n", data_normalized_l2)