# -*- coding: utf-8 -*-
"""LR_1_task_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/138amNn1q-3g_YlsWNzXqs9JG8KzETzgb
"""

# Імпорт необхідних бібліотек
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
from utilities import visualize_classifier

# Визначення зразка вхідних даних
X = np.array([
    [3.1, 7.2], [4.0, 6.7], [2.9, 8.0],
    [5.1, 4.5], [6.0, 5.0], [5.6, 5.0],
    [3.3, 0.4], [3.9, 0.9], [2.8, 1.0],
    [0.5, 3.4], [1.0, 4.0], [0.6, 4.9]
])

# Відповідні мітки класів
y = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3])

# Створення об'єкта логістичного класифікатора
classifier = linear_model.LogisticRegression(solver='liblinear', C=1)

# Тренування класифікатора на основі даних
classifier.fit(X, y)

# Візуалізація результатів класифікації
visualize_classifier(classifier, X, y)