# -*- coding: utf-8 -*-
"""LR_4_task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5BRwBUYGe1lQCnA2SYHGi65MfsiZcAy
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin

# Завантажуємо набір даних Iris
iris = load_iris()
X = iris['data']
y = iris['target']

# 1. Кластеризація KMeans з 3 кластерами
kmeans_3 = KMeans(n_clusters=3, random_state=42)
kmeans_3.fit(X)
y_kmeans_3 = kmeans_3.predict(X)

# Виведення графіка кластеризації з 3 кластерами
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y_kmeans_3, s=50, cmap='viridis')
centers = kmeans_3.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)
plt.title('Кластеризація KMeans (3 кластери)')
plt.show()

# 2. Кластеризація KMeans з 8 кластерами (порівняння)
kmeans_8 = KMeans(n_clusters=8, random_state=42)
kmeans_8.fit(X)
y_kmeans_8 = kmeans_8.predict(X)

# Виведення графіка кластеризації з 8 кластерами
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=y_kmeans_8, s=50, cmap='viridis')
centers = kmeans_8.cluster_centers_
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)
plt.title('Кластеризація KMeans (8 кластерів)')
plt.show()

# 3. Ручна кластеризація
def find_clusters(X, n_clusters, rseed=2):
    rng = np.random.RandomState(rseed)
    i = rng.permutation(X.shape[0])[:n_clusters]
    centers = X[i]
    while True:
        labels = pairwise_distances_argmin(X, centers)
        new_centers = np.array([X[labels == i].mean(0) for i in range(n_clusters)])
        if np.all(centers == new_centers):
            break
        centers = new_centers
    return centers, labels

# Виконання ручної кластеризації
centers, labels = find_clusters(X, 3)

# Виведення графіка ручної кластеризації
plt.figure(figsize=(8, 6))
plt.scatter(X[:, 0], X[:, 1], c=labels, s=50, cmap='viridis')
plt.scatter(centers[:, 0], centers[:, 1], c='black', s=200, alpha=0.5)
plt.title('Ручна кластеризація (3 кластери)')
plt.show()